###
GET http://localhost:54111/findAll_v1

###
GET http://localhost:54111/count


###
POST http://localhost:54111/user
Content-Type: application/json

{
  "username": "97defa56",
  "password": "19dd21ca",
  "email": "a07051cb",
  "sex": "85abefb9",
  "age": 5,
  "status": "normal"
}